import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import './css/tokens.css'
import styles from "@/app/page.module.css";
import globalStyles from "@/app/css/styles.module.css";

import Header from "@/app/header/Header";
import {ConcatClasses} from "@/helpers/helpers";
import Providers from "@/app/providers";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <Providers>

        <body className={ConcatClasses(inter.className, styles.body, 'body-text')}>
        <Header/>
        <main>
            <div className={globalStyles.wrapper}>
                {children}
            </div>
        </main>
        </body>
        </Providers>
        </html>
    )
}
